# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  主页: /
  归档: archives
  分类: categories
  标签: tags
  关于: about
  English: http://jilongliao.com


# Set default keywords (Use a comma to separate)
keywords: "生命,真理,信仰,人生"

# Put your favicon.ico into `hexo-site/themes/hipaper/source/` directory.
favicon: css/images/favicon.ico


# Put your avatar.jpg into `hexo-site/themes/hipaper/source/` directory.
# url is target link (E.g. `url: https://hexo.io/logo.svg` or `url: css/images/mylogo.jpg`)
avatar: 
  enable: false
  width: 124
  height: 124
  bottom: 10
  url: https://hexo.io/logo.svg


# AboutPage background, support multiple images.
about_big_image:


# Homepage thumbnail
random_thumb: false


# Content
fancybox: true


# Sidebar
sidebar: right
widgets:
#- search
- social
- recent_posts
- tagcloud

# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Github: https://github.com/little-eyes
  #Weibo: 
  #Twitter: 
  #Facebook: 
  #Google-plus: 
  #Instagram: 


# Search
search:
    insight: false # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: false # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false


# comment ShortName, you can choose only ONE to display.
duoshuo_shortname: jilongliao
disqus_shortname: 


# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:
baidu_site_verification:
qihu_site_verification:

# Miscellaneous
google_analytics:
gauges_analytics:
baidu_analytics:
tencent_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: true
  app_id: 312094928877205      #<app_id>
  fb_admin: 937628096267431    #<user_id>
  like_button:  true
  webmaster:    true

# CNZZ count
cnzz_siteid: 1260716016